---
title: "MRI merge - WJ No Impute"
author: "Kayleigh Ryherd"
date: "12/5/2017"
output: html_document
---

```{r}
library(data.table)
library(xtable)
setwd("~/Dropbox/Definition_of_PCs/RegressionDefinitionMethod/MultipleCompTests-Aug2017/RegressionMethod/CheckingInfluentialPoints_Nov292017/Analysis_May2018")
MRI <- read.csv("FullData_Dec5_2017.csv")
dfs <- list("WJ3NoImputeInt-10_70.csv",
            "WJ3NoImputeInt-20_65.csv",
            "WJ3NoImputeInt-20_70.csv", 
            "WJ3NoImputeInt-15_65.csv", 
            "WJ3NoImputeNoInt-20_70.csv",
            "WJ3NoImputeNoInt-15_70.csv",
            "WJ3NoImputeNoInt-20_65.csv", 
            "WJ3NoImputeNoInt-15_65.csv", 
            "WJ3NoImputeNoInt-10_70.csv")
data.groups <- lapply(dfs, read.csv)
data.groups <- lapply(data.groups, function(x) { x["X"] <- NULL; x })
data.groups <- lapply(data.groups, function(x) { x["X.1"] <- NULL; x })

# remove EPCs
newList <- list()
for (i in 1:length(data.groups)) {
  new <- subset(data.groups[[i]], CI_group != "EPC")
  new$CI_group <- factor(new$CI_group)
  newList[[i]] <- new
}

# merge MRI IDs
mergeList <- list()
for (i in 1:length(newList)) {
merged <- merge(newList[[i]], MRI, by.x = "SubjectID", by.y = "SubjectID", all = TRUE)
merged2 <- merged[,c(1, 13, 15, 17, 28, 29, 47, 48)]
merged3 <- merged2[complete.cases(merged2$StructuralMRI.ID),]
mergeList[[i]] <- merged3
}

# create counts of subjects in each group that have MRI data
tableList <- list()
for (i in 1:length(mergeList)) {
  table <- table(mergeList[[i]]$CI_group)
  tableList[[i]] <- table
}

names(tableList) <- dfs

results <- data.frame(do.call("rbind", tableList))
Model <- rownames(results)
Model <- gsub('.csv', '', Model)
results <- cbind(Model, results)

write.csv(results, "MRIMergeNotImputedModels.csv")

names(mergeList) <- dfs
list2env(mergeList,envir=.GlobalEnv)
```

```{r, results = "asis"}

rs <- xtable(results)
print(rs, type ="html", include.rownames = FALSE)
```


```{r}

WJ3.list <- dfs <- list(`WJ3NoImputeInt-10_70.csv`,
            `WJ3NoImputeInt-20_65.csv`,
            `WJ3NoImputeInt-20_70.csv`, 
            `WJ3NoImputeInt-15_65.csv`, 
            `WJ3NoImputeNoInt-20_70.csv`,
            `WJ3NoImputeNoInt-15_70.csv`,
            `WJ3NoImputeNoInt-20_65.csv`, 
            `WJ3NoImputeNoInt-15_65.csv`, 
            `WJ3NoImputeNoInt-10_70.csv`)
names(WJ3.list) <- c("WJ3NoImputeInt-10_70.csv",
            "WJ3NoImputeInt-20_65.csv",
            "WJ3NoImputeInt-20_70.csv", 
            "WJ3NoImputeInt-15_65.csv", 
            "WJ3NoImputeNoInt-20_70.csv",
            "WJ3NoImputeNoInt-15_70.csv",
            "WJ3NoImputeNoInt-20_65.csv", 
            "WJ3NoImputeNoInt-15_65.csv", 
            "WJ3NoImputeNoInt-10_70.csv")

group.diffs <- list("wj3.rcomp.t", "age.mri", "wasi.matr.t", "decoding.comp", "ppvt.t")

group.diffs.list <- list()
for (j in group.diffs) {
  form <- substitute(j ~ CI_group, list(j = as.name(j)))
  form <- as.formula(form)
  ares <- data.frame()
  for (i in 1:length(WJ3.list)){
    a1 <- aov(form, data = WJ3.list[[i]])
    p.val <- summary(a1)[[1]][[1,"Pr(>F)"]]
    ares <- rbind(ares, c(i,p.val))
  }
  Model <- gsub('.csv', '', names(WJ3.list))
  ares2 <- data.frame(cbind(Model, ares[,2]))
  colnames(ares2)[2] <- "P-Val"
  ares2$`P-Val`<- as.numeric(as.character(ares2$`P-Val`))
  ares2$Sig[ares2$`P-Val` < .05] <- "*"
  group.diffs.list[[j]] <- ares2
}
names(group.diffs.list) <- c("ReadingComp", "Age", "MR", "Decode", "PPVT")
list2env(group.diffs.list,envir=.GlobalEnv)


write.csv(ReadingComp, "ReadingCompNoImpute.csv")
write.csv(Age, "AgeNoImpute.csv")
write.csv(MR, "MatrixReasoningNoImpute.csv")
write.csv(Decode, "DecodingNoImpute.csv")
write.csv(PPVT, "VocabNoImpute.csv")
 
```

```{r}
printList <- list(`WJ3NoImputeInt-15_70.csv`,`WJ3NoImputeInt-15_65.csv`,`WJ3NoImputeNoInt-15_65.csv`,`WJ3NoImputeNoInt-15_70.csv`)
newprintList <- list()
for (i in 1:length(printList)) {
  print <- printList[[i]][,c(1,5,6,7)]
  print <- print[!is.na(print$CI_group),]
  newprintList[[i]] <- print
}
names(newprintList) <- c("WJ3NoImputeInt-15_70", "WJ3NoImputeInt-15_65", "WJ3NoImputeNoInt-15_65","WJ3NoImputeNoInt-15_70")
list2env(newprintList,envir=.GlobalEnv)

write.csv(`WJ3NoImputeInt-15_65`, "WJ3NoImputeInt-15_65_Apr3.csv")
write.csv(`WJ3NoImputeInt-15_70`, "WJ3NoImputeInt-15_70_Apr3.csv")
write.csv(`WJ3NoImputeNoInt-15_65`, "WJ3NoImputeNoInt-15_65_Apr3.csv")
write.csv(`WJ3NoImputeNoInt-15_70`, "WJ3NoImputeNoInt-15_70_Apr3.csv")

```


```{r}

# plot creation
library(ggplot2)
library(gridExtra)
library(plyr)
library(ggsignif)


WJ3NoImputeInt10_70 <- mergeList[[1]]
WJ3NoImputeNoInt10_70 <- mergeList[[9]]
WJ3NoImputeInt15_65 <- mergeList[[4]]
WJ3NoImputeInt20_70 <- mergeList[[3]]


p1_sum<-ddply(WJ3NoImputeInt10_70, c("CI_group"), summarize,
              AVERAGE=mean(wasi.matr.t, na.rm = TRUE),
              SE=sqrt(var(wasi.matr.t, na.rm = TRUE)/length(wasi.matr.t)))
p1 <- ggplot(aes(CI_group, wasi.matr.t, fill = CI_group), data = WJ3NoImputeInt10_70[!is.na(WJ3NoImputeInt10_70$CI_group),]) + 
  geom_violin() + ggtitle("WJ3NoImputeInt-10_70") + theme_classic() + 
  geom_point(aes(y = AVERAGE), size = 2, position = position_dodge((width = 0.90)), data = p1_sum) + 
  geom_errorbar(aes(y = AVERAGE, ymin = AVERAGE-SE, ymax = AVERAGE+SE), 
                width = 0.20, position = position_dodge((width = 0.90)), data = p1_sum) +
  geom_signif(comparisons = list(c("EAC", "UPC")), annotation="NS (p = .675)", tip_length=0) + ylim(NA,2.5)
p1

p2_sum<-ddply(WJ3NoImputeNoInt10_70, c("CI_group"), summarize,
              AVERAGE=mean(wasi.matr.t, na.rm = TRUE),
              SE=sqrt(var(wasi.matr.t, na.rm = TRUE)/length(wasi.matr.t)))
p2 <- ggplot(aes(CI_group, wasi.matr.t, fill = CI_group), data = WJ3NoImputeNoInt10_70[!is.na(WJ3NoImputeNoInt10_70$CI_group),]) + 
  geom_violin() + ggtitle("WJ3NoImputeNoInt-10_70") + theme_classic() + 
  geom_point(aes(y = AVERAGE), size = 2, position = position_dodge((width = 0.90)), data = p2_sum) + 
  geom_errorbar(aes(y = AVERAGE, ymin = AVERAGE-SE, ymax = AVERAGE+SE), 
                width = 0.20, position = position_dodge((width = 0.90)), data = p2_sum) +
  geom_signif(comparisons = list(c("EAC", "UPC")), annotation="NS (p = .517)", tip_length=0) + ylim(NA,2.5)
p2

p3_sum<-ddply(WJ3NoImputeNoInt10_70, c("CI_group"), summarize,
              AVERAGE=mean(wasi.matr.t, na.rm = TRUE),
              SE=sqrt(var(wasi.matr.t, na.rm = TRUE)/length(wasi.matr.t)))
p3 <- ggplot(aes(CI_group, wasi.matr.t, fill = CI_group), data = WJ3NoImputeInt15_65[!is.na(WJ3NoImputeInt15_65$CI_group),]) + 
  geom_violin() + ggtitle("WJ3NoImputeInt-15_65") + theme_classic() + 
  geom_point(aes(y = AVERAGE), size = 2, position = position_dodge((width = 0.90)), data = p3_sum) + 
  geom_errorbar(aes(y = AVERAGE, ymin = AVERAGE-SE, ymax = AVERAGE+SE), 
                width = 0.20, position = position_dodge((width = 0.90)), data = p3_sum) +
  geom_signif(comparisons = list(c("EAC", "UPC")), annotation="* (p = .042)", tip_length=0) + ylim(NA,3)
p3

p4_sum<-ddply(WJ3NoImputeInt20_70, c("CI_group"), summarize,
              AVERAGE=mean(wasi.matr.t, na.rm = TRUE),
              SE=sqrt(var(wasi.matr.t, na.rm = TRUE)/length(wasi.matr.t)))
p4 <- ggplot(aes(CI_group, wasi.matr.t, fill = CI_group), data = WJ3NoImputeInt20_70[!is.na(WJ3NoImputeInt20_70$CI_group),]) + 
  geom_violin() + ggtitle("WJ3NoImputeInt-15_65") + theme_classic() + 
  geom_point(aes(y = AVERAGE), size = 2, position = position_dodge((width = 0.90)), data = p4_sum) + 
  geom_errorbar(aes(y = AVERAGE, ymin = AVERAGE-SE, ymax = AVERAGE+SE), 
                width = 0.20, position = position_dodge((width = 0.90)), data = p4_sum) +
  geom_signif(comparisons = list(c("EAC", "UPC")), annotation="marginal (p = .073)", tip_length=0) + ylim(NA,3)
p4

grid.arrange(p1,p2,p3,p4, ncol = 2)

```