  ---
title: "Merging with MRI data"
author: "Kayleigh Ryherd"
date: "9/14/2017"
output: html_document
---

```{r, warning = FALSE, message = FALSE}
library(data.table)
library(xtable)
setwd("~/Dropbox/Definition_of_PCs/RegressionDefinitionMethod/MultipleCompTests-Aug2017/RegressionMethod")
MRI <- read.csv("FullData_FinalMay23_2017.csv")
dfs <- list("WJInt-20_70.csv", "WJNoInt-20_70.csv", "KTEAInt-20_70.csv", "KTEANoInt-20_70.csv",
            "WJInt-15_70.csv", "WJNoInt-15_70.csv", "KTEAInt-15_70.csv", "KTEANoInt-15_70.csv",
            "WJInt-15_60.csv", "WJNoInt-15_60.csv", "KTEAInt-15_60.csv", "KTEANoInt-15_60.csv",
            "WJInt-15_65.csv", "WJNoInt-15_65.csv", "KTEAInt-15_65.csv", "KTEANoInt-15_65.csv",
            "CompositeInt-20_70.csv", "CompositeNoInt-20_70.csv", "CompositeInt-15_70.csv", 
            "CompositeNoInt-15_70.csv", "CompositeInt-15_65.csv", "CompositeNoInt-15_65.csv", 
            "CompositeInt-15_60.csv", "CompositeNoInt-15_60.csv")
data.groups <- lapply(dfs, read.csv)

# remove EPCs
newList <- list()
for (i in 1:length(data.groups)) {
  new <- subset(data.groups[[i]], CI_group != "EPC")
  new$CI_group <- factor(new$CI_group)
  newList[[i]] <- new
}

# merge MRI IDs
mergeList <- list()
for (i in 1:length(newList)) {
merged <- merge(newList[[i]], MRI, by.x = "SubjectID", by.y = "SubjectID", all = TRUE)
merged2 <- merged[,c(1, 4, 14, 16, 18, 20, 22, 27, 25, 26, 46)]
merged3 <- merged2[complete.cases(merged2$StructuralMRI.ID),]
mergeList[[i]] <- merged3
}

# create counts of subjects in each group that have MRI data
tableList <- list()
for (i in 1:length(mergeList)) {
  table <- table(mergeList[[i]]$CI_group)
  tableList[[i]] <- table
}

names(tableList) <- dfs

results <- data.frame(do.call("rbind", tableList))
Model <- rownames(results)
Model <- gsub('.csv', '', Model)
results <- cbind(Model, results)

write.csv(results, "MRIMergeAllModels.csv")

names(mergeList) <- dfs
list2env(mergeList,envir=.GlobalEnv)

WJInt15_60 <- `WJInt-15_60.csv`[complete.cases(`WJInt-15_60.csv`[,c(1,4,8,9)]),c(1,4,8,9)]
KTEANoInt15_65 <- `KTEANoInt-15_65.csv`[complete.cases(`KTEANoInt-15_65.csv`[,c(1,4,5,8,9)]),c(1,4,5,8,9)]
KTEAInt15_60 <- `KTEAInt-15_60.csv`[complete.cases(`KTEAInt-15_60.csv`[,c(1,4,8,9)]),c(1,4,8,9)]
CompositeInt20_70 <- `CompositeInt-20_70.csv`[complete.cases(`CompositeInt-20_70.csv`[,c(1,4,8,9)]),c(1,4,8,9)]
```

```{r, results = "asis"}

rs <- xtable(results)
print(rs, type ="html", include.rownames = FALSE)
```


```{r}

ktea.list <- dfs <- list("KTEAInt-20_70.csv", "KTEANoInt-20_70.csv","KTEAInt-15_70.csv", "KTEANoInt-15_70.csv",
            "KTEAInt-15_60.csv", "KTEANoInt-15_60.csv","KTEAInt-15_65.csv", "KTEANoInt-15_65.csv")
ktea.data.groups <- lapply(ktea.list, read.csv)
names(ktea.data.groups) <- ktea.list

# remove EPCs
kteaList <- list()
for (i in 1:length(ktea.data.groups)) {
  new <- subset(ktea.data.groups[[i]], CI_group != "EPC")
  new$CI_group <- factor(new$CI_group)
  kteaList[[i]] <- new
}

group.diffs <- list("ktea2.t", "age.tested.c", "wasi.matr.t", "decode.cs", "ppvt.t")

group.diffs.list <- list()
for (j in group.diffs) {
  form <- substitute(j ~ CI_group, list(j = as.name(j)))
  form <- as.formula(form)
  ares <- data.frame()
  for (i in 1:length(kteaList)){
    a1 <- aov(form, data = kteaList[[i]])
    p.val <- summary(a1)[[1]][[1,"Pr(>F)"]]
    ares <- rbind(ares, c(i,p.val))
  }
  Model <- gsub('.csv', '', ktea.list)
  ares2 <- data.frame(cbind(Model, ares[,2]))
  colnames(ares2)[2] <- "P-Val"
  ares2$`P-Val`<- as.numeric(as.character(ares2$`P-Val`))
  ares2$Sig[ares2$`P-Val` < .05] <- "*"
  group.diffs.list[[j]] <- ares2
}

list2env(group.diffs.list,envir=.GlobalEnv)


wj3.list <- dfs <- list("WJInt-20_70.csv", "WJNoInt-20_70.csv","WJInt-15_70.csv", "WJNoInt-15_70.csv",
            "WJInt-15_60.csv", "WJNoInt-15_60.csv","WJInt-15_65.csv", "WJNoInt-15_65.csv")
wj3.data.groups <- lapply(wj3.list, read.csv)
names(wj3.data.groups) <- wj3.list

# remove EPCs
wj3List <- list()
for (i in 1:length(wj3.data.groups)) {
  new <- subset(wj3.data.groups[[i]], CI_group != "EPC")
  new$CI_group <- factor(new$CI_group)
  wj3List[[i]] <- new
}

group.diffs <- list("wj3.rcomp.t", "age.tested.c", "wasi.matr.t", "decode.cs", "ppvt.t")

group.diffs.list <- list()
for (j in group.diffs) {
  form <- substitute(j ~ CI_group, list(j = as.name(j)))
  form <- as.formula(form)
  ares <- data.frame()
  for (i in 1:length(wj3List)){
    a1 <- aov(form, data = wj3List[[i]])
    p.val <- summary(a1)[[1]][[1,"Pr(>F)"]]
    ares <- rbind(ares, c(i,p.val))
  }
  Model <- gsub('.csv', '', wj3.list)
  ares2 <- data.frame(cbind(Model, ares[,2]))
  colnames(ares2)[2] <- "P-Val"
  ares2$`P-Val`<- as.numeric(as.character(ares2$`P-Val`))
  ares2$Sig[ares2$`P-Val` < .05] <- "*"
  group.diffs.list[[j]] <- ares2
}
names(group.diffs.list) <- c("ReadingComp", "Age", "MR", "Decode", "PPVT")
list2env(group.diffs.list,envir=.GlobalEnv)

composite.list <- dfs <- list("CompositeInt-20_70.csv", "CompositeNoInt-20_70.csv","CompositeInt-15_70.csv", "CompositeNoInt-15_70.csv",
            "CompositeInt-15_60.csv", "CompositeNoInt-15_60.csv","CompositeInt-15_65.csv", "CompositeNoInt-15_65.csv")
composite.data.groups <- lapply(composite.list, read.csv)
names(composite.data.groups) <- composite.list

# remove EPCs
compositeList <- list()
for (i in 1:length(composite.data.groups)) {
  new <- subset(composite.data.groups[[i]], CI_group != "EPC")
  new$CI_group <- factor(new$CI_group)
  compositeList[[i]] <- new
}

group.diffs <- list("rc.comp", "age.tested.c", "wasi.matr.t", "decode.cs", "ppvt.t")

group.diffs.list <- list()
for (j in group.diffs) {
  form <- substitute(j ~ CI_group, list(j = as.name(j)))
  form <- as.formula(form)
  ares <- data.frame()
  for (i in 1:length(compositeList)){
    a1 <- aov(form, data = compositeList[[i]])
    p.val <- summary(a1)[[1]][[1,"Pr(>F)"]]
    ares <- rbind(ares, c(i,p.val))
  }
  Model <- gsub('.csv', '', composite.list)
  ares2 <- data.frame(cbind(Model, ares[,2]))
  colnames(ares2)[2] <- "P-Val"
  ares2$`P-Val`<- as.numeric(as.character(ares2$`P-Val`))
  ares2$Sig[ares2$`P-Val` < .05] <- "*"
  group.diffs.list[[j]] <- ares2
}

names(group.diffs.list) <- c("rc.comp", "age.rc", "wasi.matr.rc", "decode.rc", "ppvt.rc")
list2env(group.diffs.list,envir=.GlobalEnv)

ReadingComp <- rbind(ktea2.t, ReadingComp, rc.comp)
Age <- rbind(age.tested.c, Age, age.rc)
Matrix.Reasoning <- rbind(wasi.matr.t, MR, wasi.matr.rc)
Decoding <- rbind(decode.cs, Decode, decode.rc)
Vocab <- rbind(ppvt.t, PPVT, ppvt.rc)

 
```

```{r}
ageList <- list(WJInt15_60, KTEAInt15_60, KTEANoInt15_65, CompositeInt20_70)

full.data <- read.csv("FullData_FinalMay23_2017.csv")
age.data <- full.data[,c(1,2)]
# merge MRI IDs

mergeList <- list()
for (i in 1:length(ageList)) {
merged <- merge(ageList[[i]], age.data, by.x = "SubjectID", by.y = "SubjectID")
mergeList[[i]] <- merged
}
names(mergeList) <- c("WJInt15_60-imputed", "KTEAInt15_60-imputed", "KTEANoInt15_65-imputed", "CompositeInt20_70-imputed")
list2env(mergeList,envir=.GlobalEnv)

write.csv(`WJInt15_60-imputed`, "WJInt15_60-imputed.csv")
write.csv(`KTEAInt15_60-imputed`, "KTEAInt15_60-imputed.csv")
write.csv(`KTEANoInt15_65-imputed`, "KTEANoInt15_65-imputed.csv")
write.csv(`CompositeInt20_70-imputed`, "CompositeInt20_70-imputed.csv")
```

